
services:
  web:
    build:
      dockerfile: ./Dockerfile
    # image: sbmtWeb
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    links:
      - db

  db:
    image: postgres:16
    container_name: sbmt_db
    ports:
      - "5551:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
