
# https://stackoverflow.com/questions/27409761/docker-multiple-dockerfiles-in-project
# https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes


services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "5001:5000"
    links:
      - db

  db:
    image: postgres:latest
    ports:
      - "5551:5432"
    environment:
      - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST_AUTH_METHOD=trust    
      # - POSTGRES_DB=postgres
    # volumes:
    #     - pgdata:/var/lib/postgresql/data
  
# volumes:
#   pgdata:
