
# https://stackoverflow.com/questions/27409761/docker-multiple-dockerfiles-in-project
# https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes

name: sbmt_dev

services:
  db:
    image: postgres:16
    container_name: sbmt_db_dev
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
        - pgdatadev:/var/lib/postgresql/data
  
volumes:
  pgdatadev:
